### ISSUE TITLE
Compiling rover-app in Raspbian

### ISSUE THREAD

**Issue by daleonpz** [app4mc-rover/rover-app#16]
I wanted to test mqtt examples on raspbian 4.14.79-v7+, but when I compile I got the following error:

```
/home/pi/git/mqqt-test/src/roverapi/rover_mqttcommand.cpp:22:23: fatal error: json/json.h: No such file or directory
 #include <json/json.h>
```

What I did:

```
git clone https://github.com/app4mc-rover/rover-app.git mqqt-test
cd mqqt-test/
mkdir build
cd build/
cmake ..
make
```

**Comment by mozcelikors** [comment]
Hi, 
For vanilla raspbian, you need to install libraries manually, to my knowledge.
So you should first compile and install jsoncpp library, in your case.
Then locally edit cmake to include_directories( ${jsoncpp_INCLUDE_DIRS}), that will add -I/usr/include/jsoncpp or something similar to CFLAGS.
Have a look at CMakeLists.txt and install what packages are needed.

**Comment by mozcelikors** [comment]
Also, please have a look at https://app4mc-rover.github.io/rover-docs/content/installation.html for installation instructions for some of the packages.

**Comment by daleonpz** [comment]
I had to reinstall jsoncpp. it compiled
